### PR TITLE
Migrate to browser-sync-v3 fork

### PR DESCRIPTION
**Pull request by janbrasna**
Fixes #220, https://github.com/mozilla/ssl-config-generator/pull/218#issuecomment-1875926219

Replacing:

```diff
-const BrowserSyncWebpackPlugin = require('browser-sync-webpack-plugin');
+const BrowserSyncWebpackPlugin = require('browser-sync-v3-webpack-plugin');
```

with updated fork.

Browser-sync in v3.x removed `localtunnel` thus `axios` which points in v2.x to a vulnerable version:/

However the webpack plugin while fully compatible with v3.x is not updated to allow for the higher peerDependency version by a trivial condition [`@f3e9ead`](https://github.com/Va1/browser-sync-webpack-plugin/pull/96/commits/f3e9ead0be1536fb7f1e9cd68aa9a59c7d5e0d20) and the lack of any news about https://github.com/Va1/browser-sync-webpack-plugin/pull/96 makes it look rather abandoned.

At the same time dependabot will be trying to upgrade browser-sync to 3.x over and over without checking for failed peerDependency in a devDependency (`watch` fails but `build` passes so dependabot is happy…) so this PR resolves the issue by using a v3-compatible fork — the only change is allowing the higher peerDependecy version: [madbucket/browser-sync-webpack-plugin`@46132d8`](https://github.com/Va1/browser-sync-webpack-plugin/commit/46132d80f4c51729724ba028c133ebbafcfd38b8)

May be reverted later if the og plugin gets the compatibility fix released.

Also postcss-loader is updated to the highest compatible version (that comes with dropping support for webpack 4, only webpack 5+ is now compatible) — upgrading past the v8.x breaking release would mean Node 18+ only which I'm not sure we want to do right now so left it at the most recent v7.x version that's pretty much on par and keeping the same compatibility.

Works fine (=tested) with Node versions 16, 18, 20 (LTS); might even support Node 14 _(where the only limit in lockfile/engines is node-sass 9+ but that should not be needed as it's only optional peer dep and we use sass 1.x instead and that should run just fine even on the latest point releases of Node 14 if needed.)_

Supersedes #234, #233, #219, #193

### CODE REVIEW

**Review by caleb-pierce — APPROVED** [review]
Tested these changes locally.  Works for me. This would close a security hole in the original browser-sync-webpack-plugin which appears abandoned since 2020.

**Review by TJCrouch — APPROVED** [review]
Tested locally, and the updates look to be working properly to me.  +1 for shoring up security vulnerabilities.

**Review by chrisd1997 — APPROVED** [review]
Looks good!

**Comment by gstrauss** [comment]
All three reviewers of this PR have approved.

I am going to attempt to remove the reviewers to see if github will let me merge the pull request through the GUI.

**Review by gstrauss — APPROVED** [review]

**Comment by gstrauss** [comment]
I don't seem to have the ability in the GUI to remove reviewers.  I will attempt to merge and push via command line.

...That resulted in:
```
$ git push origin master
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 2.52 KiB | 258.00 KiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: 
remote: - New changes require approval from someone other than the last pusher.
To github.com:mozilla/ssl-config-generator
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:mozilla/ssl-config-generator'
```

Therefore, I have added myself as reviewer, approved, and now I can "Merge pull request" via the GUI.

**Comment by gstrauss** [comment]
(@janbrasna you merged moments before I did :smile:)

**Comment by janbrasna** [comment]
@gstrauss TBH I seem to be running into various branch protections randomly too, chances are existing PRs will be a little more finicky to get through the door, but the wrinkles will hopefully iron itself out over time;) Thanks.

**Pull request merged**
