### PR TITLE
Fix deploy-to-production artifact action version

### PR DESCRIPTION
**Pull request by janbrasna**
Fixup #236

### CODE REVIEW

**Review by gstrauss — APPROVED** [review]

**Comment by gstrauss** [comment]
@janbrasna FYI, you may assign yourself as a reviewer and then self-approve the review.  Then you'll be able to merge.

**Comment by gstrauss** [comment]
Now I see updates reflected in https://ssl-config.mozilla.org/

I hadn't caught the upload-pages-artifact version when reviewing.  Thanks for fixing it!

**Comment by gstrauss** [comment]
Sorry, I should have caught the failure in the github actions error log.  Thanks for fixing it!

**Comment by janbrasna** [comment]
@gstrauss Well, NOW I can;) but the protections were there before, even with 0 required approvals the default branch was still protected from pushing PRs that the actor is the last to push to it, irrelevant who is the author or reviewer (and authors were not allowed approving reviews, either…) — but generally I'd like to only self-r+ on things I broke myself to just fix up, or if something needs shipping like right now for a reason.

**Comment by janbrasna** [comment]
Actions validation is hard, some things are caught by the editor, some not, and some validations only trigger after pushing to master, so… eh. The same will be with Dependabot configs, they usually take a few attempts to actually get right;) so no worries, this needs a few dry runs off of a fork's default branch to get the real annotations et al., and this was a stupid last-minute addition that seemed like a no brainer. Well…

**Pull request merged**
